### ISSUE TITLE
Не обрабатывается валидный ответ API

### ISSUE THREAD

**Issue by comradefuzz** [ApexWire/yii2-restclient#17]
При запросе несуществующего элемента данных RESTful API возвращает валидный ответ `404 Not Found`. В этом случае при обращении `$model = Account::findOne(['id' => $id]);` выдает `GuzzleHttp\Exception\ClientException`, а должен был вернуть `null`.

Если отключать `http_errors` в настройках guzzle, то ответ с ошибкой воспринимается, как данные:
```
Unknown Property – yii\base\UnknownPropertyException

Attribute `id` not found in API response. Available fields: name, message, code, status, type.
```

Как предполагается решать такие ситуации?

**Comment by ApexWire** [comment]
Реализация для таких ситуаций не была предусмотрена.
Ваш PR приму после небольшой корректировки: false заменить на null

**Comment by comradefuzz** [comment]
Так и было задумано, но `null` не проходит [это условие](https://github.com/ApexWire/yii2-restclient/blob/master/src/RestQuery.php#L167-L168), что вызывает ошибку:
```
public function one($db = null)
    {
        $row = parent::one($db);
        if ($row !== false) {
            $models = $this->populate(isset($row[0]) ? $row : [$row]);
            return reset($models) ?: null;
        }
        return null;
    }
```

**Comment by ApexWire** [comment]
Принял PR
