### ISSUE TITLE
Отличия от yii2-hiart

### ISSUE THREAD

**Issue by hiqsol** [ApexWire/yii2-restclient#4]
Опишите, пожалуйста, в самых общих чертах, что уже меняли и со временем дописывайте что ещё меняете.
Я буду отслеживать.
Спасибо!

**Comment by ApexWire** [comment]
Тут: https://github.com/ApexWire/yii2-restclient/releases/tag/0.1 - в общих чертах описал что менялось. По возможности буду добавлять изменения

**Comment by hiqsol** [comment]
ok, спасибо!

2016-03-11 16:48 GMT+02:00 ApexWire notifications@github.com:

**Comment by ApexWire** [comment]
Веду список изменений тут: https://github.com/ApexWire/yii2-restclient/blob/master/CHANGELOG.md
